baseurl = "https://365.felixparadis.com"
title = "365 - Félix Paradis"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "blsfljksfiou"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

googleAnalytics = "UA-109396923-1"
[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[params]
    author = "Félix Paradis"
    description = "Felix Paradis's photographic work."
    keywords = "photography,travel"
    images = ["images/profile.png"] # for og:image

    # favicon_32 = "/img/favicon-32x32.png"
    # favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = false

    # Specify colorscheme. Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    custom_css = []
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "dracula"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/FelDev/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 2
    url = "https://medium.com/@FelixParadis"
[[params.social]]
    name = "CodePen"
    icon = "fab fa-codepen fa-2x"
    weight = 5
    url = "https://codepen.io/FelDev/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/felix-paradis/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 6
    url = "https://twitter.com/felixs_username/"
[[params.social]]
    name = "Stack Exchange"
    icon = "fab fa-stack-exchange fa-2x"
    weight = 3
    url = "https://stackexchange.com/users/7861276/feldev?tab=accounts"

[languages]
    [languages.en]
        languagename = "English"
        
        # Menu links
        [languages.en.menu]

    # [languages.fr-ca]
    #     languagename = "Français"
    #     title = "Félix Paradis"

    #     [languages.fr-ca.params]
    #         author = "Félix Paradis"
    #         info = "Enchanté"
    #         description = "Site personnel de Félix Paradis"
    #         keywords = "blog,code,personnel"
    #         footercontent = "Super nice."

    #     # Menu links
    #     [languages.fr-ca.menu]

    #         # [[languages.fr-ca.menu.main]]
    #         # name = "À propos"
    #         # weight = 1
    #         # url = "about/"

    #         # [[languages.fr-ca.menu.main]]
    #         # name = "Blog"
    #         # weight = 2
    #         # url = "posts/"

    #         [[languages.fr-ca.menu.main]]
    #         name = "Projets"
    #         weight = 3
    #         url = "projects/"

    #         [[languages.fr-ca.menu.main]]
    #         name = "Contact"
    #         weight = 5
    #         url = "contact/"