[context.production.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "12"

[[redirects]]
  from = "/admin"
  to = "https://www.felixparadis.com/admin"
  status = 301
  force = false
[[redirects]]
  from = "/wp-admin"
  to = "https://www.felixparadis.com/admin"
  status = 301
  force = false
[[redirects]]
  from = "/*.php"
  to = "https://www.felixparadis.com/admin"
  status = 301
  force = false
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"  
  status = 200
